version: "3.9"
services:
  web:
    build:
      context: ./
      dockerfile: tomcat.dockerfile
    ports:
      - "8080:8080"
  postgres:
    build:
      context: ./
      dockerfile: postgres.dockerfile
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
